package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderReturnApply;
import org.linlinjava.litemall.db.domain.LitemallOrderReturnApplyExample;
import org.linlinjava.litemall.db.domain.LitemallOrderReturnApplyResult;
import org.linlinjava.litemall.db.domain.LitemallReturnApplyQueryParam;

public interface LitemallOrderReturnApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int insert(LitemallOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnApply selectOneByExample(LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnApply selectOneByExampleSelective(@Param("example") LitemallOrderReturnApplyExample example, @Param("selective") LitemallOrderReturnApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallOrderReturnApply> selectByExampleSelective(@Param("example") LitemallOrderReturnApplyExample example, @Param("selective") LitemallOrderReturnApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    List<LitemallOrderReturnApply> selectByExample(LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnApply selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallOrderReturnApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    LitemallOrderReturnApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderReturnApply record, @Param("example") LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderReturnApply record, @Param("example") LitemallOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderReturnApply record);

    /**
     * 查询申请列表
     */
    List<LitemallOrderReturnApply> getList(@Param("queryParam") LitemallReturnApplyQueryParam queryParam);

    /**
     * 获取申请详情
     */
    LitemallOrderReturnApplyResult getDetail(@Param("id") Long id);
}