package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderReturnReason;
import org.linlinjava.litemall.db.domain.LitemallOrderReturnReasonExample;

public interface LitemallOrderReturnReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int insert(LitemallOrderReturnReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderReturnReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnReason selectOneByExample(LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnReason selectOneByExampleSelective(@Param("example") LitemallOrderReturnReasonExample example, @Param("selective") LitemallOrderReturnReason.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallOrderReturnReason> selectByExampleSelective(@Param("example") LitemallOrderReturnReasonExample example, @Param("selective") LitemallOrderReturnReason.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    List<LitemallOrderReturnReason> selectByExample(LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderReturnReason selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallOrderReturnReason.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    LitemallOrderReturnReason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderReturnReason record, @Param("example") LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderReturnReason record, @Param("example") LitemallOrderReturnReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderReturnReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_reason
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderReturnReason record);
}