package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class LitemallOrderReturnApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    private Long companyAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.member_username
     *
     * @mbg.generated
     */
    private String memberUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    private BigDecimal returnAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.return_name
     *
     * @mbg.generated
     */
    private String returnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    private String returnPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    private String productPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    private String productAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_count
     *
     * @mbg.generated
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    private BigDecimal productRealPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    private String proofPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    private String handleNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    private String handleMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    private String receiveMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    private String receiveNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.id
     *
     * @return the value of litemall_order_return_apply.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.id
     *
     * @param id the value for litemall_order_return_apply.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.order_id
     *
     * @return the value of litemall_order_return_apply.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.order_id
     *
     * @param orderId the value for litemall_order_return_apply.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.company_address_id
     *
     * @return the value of litemall_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    public Long getCompanyAddressId() {
        return companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.company_address_id
     *
     * @param companyAddressId the value for litemall_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    public void setCompanyAddressId(Long companyAddressId) {
        this.companyAddressId = companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_id
     *
     * @return the value of litemall_order_return_apply.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_id
     *
     * @param productId the value for litemall_order_return_apply.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.order_sn
     *
     * @return the value of litemall_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.order_sn
     *
     * @param orderSn the value for litemall_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.create_time
     *
     * @return the value of litemall_order_return_apply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method sets the value of the database column litemall_order_return_apply.create_time
     *
     * @param createTime the value for litemall_order_return_apply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.member_username
     *
     * @return the value of litemall_order_return_apply.member_username
     *
     * @mbg.generated
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.member_username
     *
     * @param memberUsername the value for litemall_order_return_apply.member_username
     *
     * @mbg.generated
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.return_amount
     *
     * @return the value of litemall_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    public BigDecimal getReturnAmount() {
        return returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.return_amount
     *
     * @param returnAmount the value for litemall_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    public void setReturnAmount(BigDecimal returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.return_name
     *
     * @return the value of litemall_order_return_apply.return_name
     *
     * @mbg.generated
     */
    public String getReturnName() {
        return returnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.return_name
     *
     * @param returnName the value for litemall_order_return_apply.return_name
     *
     * @mbg.generated
     */
    public void setReturnName(String returnName) {
        this.returnName = returnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.return_phone
     *
     * @return the value of litemall_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    public String getReturnPhone() {
        return returnPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.return_phone
     *
     * @param returnPhone the value for litemall_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    public void setReturnPhone(String returnPhone) {
        this.returnPhone = returnPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.status
     *
     * @return the value of litemall_order_return_apply.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.status
     *
     * @param status the value for litemall_order_return_apply.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.handle_time
     *
     * @return the value of litemall_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.handle_time
     *
     * @param handleTime the value for litemall_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_pic
     *
     * @return the value of litemall_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_pic
     *
     * @param productPic the value for litemall_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_name
     *
     * @return the value of litemall_order_return_apply.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_name
     *
     * @param productName the value for litemall_order_return_apply.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_brand
     *
     * @return the value of litemall_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_brand
     *
     * @param productBrand the value for litemall_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_attr
     *
     * @return the value of litemall_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_attr
     *
     * @param productAttr the value for litemall_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_count
     *
     * @return the value of litemall_order_return_apply.product_count
     *
     * @mbg.generated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_count
     *
     * @param productCount the value for litemall_order_return_apply.product_count
     *
     * @mbg.generated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_price
     *
     * @return the value of litemall_order_return_apply.product_price
     *
     * @mbg.generated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_price
     *
     * @param productPrice the value for litemall_order_return_apply.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.product_real_price
     *
     * @return the value of litemall_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    public BigDecimal getProductRealPrice() {
        return productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.product_real_price
     *
     * @param productRealPrice the value for litemall_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    public void setProductRealPrice(BigDecimal productRealPrice) {
        this.productRealPrice = productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.reason
     *
     * @return the value of litemall_order_return_apply.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.reason
     *
     * @param reason the value for litemall_order_return_apply.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.description
     *
     * @return the value of litemall_order_return_apply.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.description
     *
     * @param description the value for litemall_order_return_apply.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.proof_pics
     *
     * @return the value of litemall_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    public String getProofPics() {
        return proofPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.proof_pics
     *
     * @param proofPics the value for litemall_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    public void setProofPics(String proofPics) {
        this.proofPics = proofPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.handle_note
     *
     * @return the value of litemall_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    public String getHandleNote() {
        return handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.handle_note
     *
     * @param handleNote the value for litemall_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    public void setHandleNote(String handleNote) {
        this.handleNote = handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.handle_man
     *
     * @return the value of litemall_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    public String getHandleMan() {
        return handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.handle_man
     *
     * @param handleMan the value for litemall_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    public void setHandleMan(String handleMan) {
        this.handleMan = handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.receive_man
     *
     * @return the value of litemall_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    public String getReceiveMan() {
        return receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.receive_man
     *
     * @param receiveMan the value for litemall_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    public void setReceiveMan(String receiveMan) {
        this.receiveMan = receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.receive_time
     *
     * @return the value of litemall_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.receive_time
     *
     * @param receiveTime the value for litemall_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_return_apply.receive_note
     *
     * @return the value of litemall_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    public String getReceiveNote() {
        return receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_return_apply.receive_note
     *
     * @param receiveNote the value for litemall_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    public void setReceiveNote(String receiveNote) {
        this.receiveNote = receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", companyAddressId=").append(companyAddressId);
        sb.append(", productId=").append(productId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", memberUsername=").append(memberUsername);
        sb.append(", returnAmount=").append(returnAmount);
        sb.append(", returnName=").append(returnName);
        sb.append(", returnPhone=").append(returnPhone);
        sb.append(", status=").append(status);
        sb.append(", handleTime=").append(handleTime);
        sb.append(", productPic=").append(productPic);
        sb.append(", productName=").append(productName);
        sb.append(", productBrand=").append(productBrand);
        sb.append(", productAttr=").append(productAttr);
        sb.append(", productCount=").append(productCount);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productRealPrice=").append(productRealPrice);
        sb.append(", reason=").append(reason);
        sb.append(", description=").append(description);
        sb.append(", proofPics=").append(proofPics);
        sb.append(", handleNote=").append(handleNote);
        sb.append(", handleMan=").append(handleMan);
        sb.append(", receiveMan=").append(receiveMan);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", receiveNote=").append(receiveNote);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallOrderReturnApply other = (LitemallOrderReturnApply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getCompanyAddressId() == null ? other.getCompanyAddressId() == null : this.getCompanyAddressId().equals(other.getCompanyAddressId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getMemberUsername() == null ? other.getMemberUsername() == null : this.getMemberUsername().equals(other.getMemberUsername()))
            && (this.getReturnAmount() == null ? other.getReturnAmount() == null : this.getReturnAmount().equals(other.getReturnAmount()))
            && (this.getReturnName() == null ? other.getReturnName() == null : this.getReturnName().equals(other.getReturnName()))
            && (this.getReturnPhone() == null ? other.getReturnPhone() == null : this.getReturnPhone().equals(other.getReturnPhone()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getHandleTime() == null ? other.getHandleTime() == null : this.getHandleTime().equals(other.getHandleTime()))
            && (this.getProductPic() == null ? other.getProductPic() == null : this.getProductPic().equals(other.getProductPic()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductBrand() == null ? other.getProductBrand() == null : this.getProductBrand().equals(other.getProductBrand()))
            && (this.getProductAttr() == null ? other.getProductAttr() == null : this.getProductAttr().equals(other.getProductAttr()))
            && (this.getProductCount() == null ? other.getProductCount() == null : this.getProductCount().equals(other.getProductCount()))
            && (this.getProductPrice() == null ? other.getProductPrice() == null : this.getProductPrice().equals(other.getProductPrice()))
            && (this.getProductRealPrice() == null ? other.getProductRealPrice() == null : this.getProductRealPrice().equals(other.getProductRealPrice()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getProofPics() == null ? other.getProofPics() == null : this.getProofPics().equals(other.getProofPics()))
            && (this.getHandleNote() == null ? other.getHandleNote() == null : this.getHandleNote().equals(other.getHandleNote()))
            && (this.getHandleMan() == null ? other.getHandleMan() == null : this.getHandleMan().equals(other.getHandleMan()))
            && (this.getReceiveMan() == null ? other.getReceiveMan() == null : this.getReceiveMan().equals(other.getReceiveMan()))
            && (this.getReceiveTime() == null ? other.getReceiveTime() == null : this.getReceiveTime().equals(other.getReceiveTime()))
            && (this.getReceiveNote() == null ? other.getReceiveNote() == null : this.getReceiveNote().equals(other.getReceiveNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getCompanyAddressId() == null) ? 0 : getCompanyAddressId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getMemberUsername() == null) ? 0 : getMemberUsername().hashCode());
        result = prime * result + ((getReturnAmount() == null) ? 0 : getReturnAmount().hashCode());
        result = prime * result + ((getReturnName() == null) ? 0 : getReturnName().hashCode());
        result = prime * result + ((getReturnPhone() == null) ? 0 : getReturnPhone().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getHandleTime() == null) ? 0 : getHandleTime().hashCode());
        result = prime * result + ((getProductPic() == null) ? 0 : getProductPic().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductBrand() == null) ? 0 : getProductBrand().hashCode());
        result = prime * result + ((getProductAttr() == null) ? 0 : getProductAttr().hashCode());
        result = prime * result + ((getProductCount() == null) ? 0 : getProductCount().hashCode());
        result = prime * result + ((getProductPrice() == null) ? 0 : getProductPrice().hashCode());
        result = prime * result + ((getProductRealPrice() == null) ? 0 : getProductRealPrice().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getProofPics() == null) ? 0 : getProofPics().hashCode());
        result = prime * result + ((getHandleNote() == null) ? 0 : getHandleNote().hashCode());
        result = prime * result + ((getHandleMan() == null) ? 0 : getHandleMan().hashCode());
        result = prime * result + ((getReceiveMan() == null) ? 0 : getReceiveMan().hashCode());
        result = prime * result + ((getReceiveTime() == null) ? 0 : getReceiveTime().hashCode());
        result = prime * result + ((getReceiveNote() == null) ? 0 : getReceiveNote().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_order_return_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        orderId("order_id", "orderId", "BIGINT", false),
        companyAddressId("company_address_id", "companyAddressId", "BIGINT", false),
        productId("product_id", "productId", "BIGINT", false),
        orderSn("order_sn", "orderSn", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        memberUsername("member_username", "memberUsername", "VARCHAR", false),
        returnAmount("return_amount", "returnAmount", "DECIMAL", false),
        returnName("return_name", "returnName", "VARCHAR", false),
        returnPhone("return_phone", "returnPhone", "VARCHAR", false),
        status("status", "status", "INTEGER", true),
        handleTime("handle_time", "handleTime", "TIMESTAMP", false),
        productPic("product_pic", "productPic", "VARCHAR", false),
        productName("product_name", "productName", "VARCHAR", false),
        productBrand("product_brand", "productBrand", "VARCHAR", false),
        productAttr("product_attr", "productAttr", "VARCHAR", false),
        productCount("product_count", "productCount", "INTEGER", false),
        productPrice("product_price", "productPrice", "DECIMAL", false),
        productRealPrice("product_real_price", "productRealPrice", "DECIMAL", false),
        reason("reason", "reason", "VARCHAR", false),
        description("description", "description", "VARCHAR", false),
        proofPics("proof_pics", "proofPics", "VARCHAR", false),
        handleNote("handle_note", "handleNote", "VARCHAR", false),
        handleMan("handle_man", "handleMan", "VARCHAR", false),
        receiveMan("receive_man", "receiveMan", "VARCHAR", false),
        receiveTime("receive_time", "receiveTime", "TIMESTAMP", false),
        receiveNote("receive_note", "receiveNote", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_return_apply
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}