package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class SmsFlashPromotionProductRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.flash_promotion_id
     *
     * @mbg.generated
     */
    private Long flashPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.flash_promotion_session_id
     *
     * @mbg.generated
     */
    private Long flashPromotionSessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.flash_promotion_price
     *
     * @mbg.generated
     */
    private BigDecimal flashPromotionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.flash_promotion_count
     *
     * @mbg.generated
     */
    private Integer flashPromotionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.flash_promotion_limit
     *
     * @mbg.generated
     */
    private Integer flashPromotionLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_product_relation.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.id
     *
     * @return the value of sms_flash_promotion_product_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.id
     *
     * @param id the value for sms_flash_promotion_product_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.flash_promotion_id
     *
     * @return the value of sms_flash_promotion_product_relation.flash_promotion_id
     *
     * @mbg.generated
     */
    public Long getFlashPromotionId() {
        return flashPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.flash_promotion_id
     *
     * @param flashPromotionId the value for sms_flash_promotion_product_relation.flash_promotion_id
     *
     * @mbg.generated
     */
    public void setFlashPromotionId(Long flashPromotionId) {
        this.flashPromotionId = flashPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.flash_promotion_session_id
     *
     * @return the value of sms_flash_promotion_product_relation.flash_promotion_session_id
     *
     * @mbg.generated
     */
    public Long getFlashPromotionSessionId() {
        return flashPromotionSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.flash_promotion_session_id
     *
     * @param flashPromotionSessionId the value for sms_flash_promotion_product_relation.flash_promotion_session_id
     *
     * @mbg.generated
     */
    public void setFlashPromotionSessionId(Long flashPromotionSessionId) {
        this.flashPromotionSessionId = flashPromotionSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.product_id
     *
     * @return the value of sms_flash_promotion_product_relation.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.product_id
     *
     * @param productId the value for sms_flash_promotion_product_relation.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.flash_promotion_price
     *
     * @return the value of sms_flash_promotion_product_relation.flash_promotion_price
     *
     * @mbg.generated
     */
    public BigDecimal getFlashPromotionPrice() {
        return flashPromotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.flash_promotion_price
     *
     * @param flashPromotionPrice the value for sms_flash_promotion_product_relation.flash_promotion_price
     *
     * @mbg.generated
     */
    public void setFlashPromotionPrice(BigDecimal flashPromotionPrice) {
        this.flashPromotionPrice = flashPromotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.flash_promotion_count
     *
     * @return the value of sms_flash_promotion_product_relation.flash_promotion_count
     *
     * @mbg.generated
     */
    public Integer getFlashPromotionCount() {
        return flashPromotionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.flash_promotion_count
     *
     * @param flashPromotionCount the value for sms_flash_promotion_product_relation.flash_promotion_count
     *
     * @mbg.generated
     */
    public void setFlashPromotionCount(Integer flashPromotionCount) {
        this.flashPromotionCount = flashPromotionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.flash_promotion_limit
     *
     * @return the value of sms_flash_promotion_product_relation.flash_promotion_limit
     *
     * @mbg.generated
     */
    public Integer getFlashPromotionLimit() {
        return flashPromotionLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.flash_promotion_limit
     *
     * @param flashPromotionLimit the value for sms_flash_promotion_product_relation.flash_promotion_limit
     *
     * @mbg.generated
     */
    public void setFlashPromotionLimit(Integer flashPromotionLimit) {
        this.flashPromotionLimit = flashPromotionLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_product_relation.sort
     *
     * @return the value of sms_flash_promotion_product_relation.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_product_relation.sort
     *
     * @param sort the value for sms_flash_promotion_product_relation.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_product_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flashPromotionId=").append(flashPromotionId);
        sb.append(", flashPromotionSessionId=").append(flashPromotionSessionId);
        sb.append(", productId=").append(productId);
        sb.append(", flashPromotionPrice=").append(flashPromotionPrice);
        sb.append(", flashPromotionCount=").append(flashPromotionCount);
        sb.append(", flashPromotionLimit=").append(flashPromotionLimit);
        sb.append(", sort=").append(sort);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_product_relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsFlashPromotionProductRelation other = (SmsFlashPromotionProductRelation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFlashPromotionId() == null ? other.getFlashPromotionId() == null : this.getFlashPromotionId().equals(other.getFlashPromotionId()))
            && (this.getFlashPromotionSessionId() == null ? other.getFlashPromotionSessionId() == null : this.getFlashPromotionSessionId().equals(other.getFlashPromotionSessionId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getFlashPromotionPrice() == null ? other.getFlashPromotionPrice() == null : this.getFlashPromotionPrice().equals(other.getFlashPromotionPrice()))
            && (this.getFlashPromotionCount() == null ? other.getFlashPromotionCount() == null : this.getFlashPromotionCount().equals(other.getFlashPromotionCount()))
            && (this.getFlashPromotionLimit() == null ? other.getFlashPromotionLimit() == null : this.getFlashPromotionLimit().equals(other.getFlashPromotionLimit()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_product_relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFlashPromotionId() == null) ? 0 : getFlashPromotionId().hashCode());
        result = prime * result + ((getFlashPromotionSessionId() == null) ? 0 : getFlashPromotionSessionId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getFlashPromotionPrice() == null) ? 0 : getFlashPromotionPrice().hashCode());
        result = prime * result + ((getFlashPromotionCount() == null) ? 0 : getFlashPromotionCount().hashCode());
        result = prime * result + ((getFlashPromotionLimit() == null) ? 0 : getFlashPromotionLimit().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sms_flash_promotion_product_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        flashPromotionId("flash_promotion_id", "flashPromotionId", "BIGINT", false),
        flashPromotionSessionId("flash_promotion_session_id", "flashPromotionSessionId", "BIGINT", false),
        productId("product_id", "productId", "BIGINT", false),
        flashPromotionPrice("flash_promotion_price", "flashPromotionPrice", "DECIMAL", false),
        flashPromotionCount("flash_promotion_count", "flashPromotionCount", "INTEGER", false),
        flashPromotionLimit("flash_promotion_limit", "flashPromotionLimit", "INTEGER", false),
        sort("sort", "sort", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sms_flash_promotion_product_relation
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}